<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="tests.PostTestCase-20200528203850" tests="10" file="tests.py" time="0.049" timestamp="2020-05-28T20:38:50" failures="1" errors="0" skipped="0">
		<testcase classname="tests.PostTestCase" name="test_task10_make_migrations" time="0.011" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="235">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task1_post_model_exists" time="0.002" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="111">
			<!--class BlogPost(models.Model):
            title = models.CharField(max_length=200)-->
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task2_author_exists" time="0.002" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="120">
			<!--author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name="posts",
        on_delete=models.CASCADE,
        )-->
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task3_body_exists" time="0.002" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="133">
			<!-- Add another field to `BlogPost` called `body` with type
        `models.TextField()`-->
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task4_postdate_exists" time="0.002" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="139">
			<!--`postdate = models.DateTimeField(auto_now_add=True, blank=True)`-->
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task5_str_exists" time="0.001" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="145">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task6_get_abs_url_exists" time="0.001" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="148">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task7_register_model_in_admin" time="0.007" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="151">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task8_update_views_with_BlogPost" time="0.009" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="173">
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
		<testcase classname="tests.PostTestCase" name="test_task9_update_post_view_with_BlogPost" time="0.012" timestamp="2020-05-28T20:38:50" file="module3\tests.py" line="208">
			<failure type="AssertionError" message="Did you remove the `try/catch` block?"><![CDATA[Traceback (most recent call last):
  File "D:\pluralsight_project\python-django-models-authentication\module3\tests.py", line 231, in test_task9_update_post_view_with_BlogPost
    self.assertTrue(try_catch_found == False, msg="Did you remove the `try/catch` block?")
  File "D:\pluralsight_project\python-django-models-authentication\support\SimplerTestCase.py", line 12, in assertTrue
    self.fail(msg or (str(expr) + "is not True"))
AssertionError: Did you remove the `try/catch` block?
]]></failure>
			<system-out><![CDATA[]]></system-out>
			<system-err><![CDATA[]]></system-err>
		</testcase>
	</testsuite>
</testsuites>
